// Preços estimados de ingredientes básicos, para a lista de mercado já mostrar um valor
// antes de o usuário importar as próprias notas fiscais.
//
// São médias de supermercado no Brasil, arredondadas — servem para ordem de grandeza,
// não para conferir o caixa. Qualquer preço importado pelo usuário (ver prices.ts) tem
// prioridade sobre estes.
//
// Unidade: 'kg' para sólidos, 'l' para líquidos, 'unidade' para o que se compra contado.

import type { PrecoItem } from '../types';
import { normalizeItemKey } from './ingredientParser';

/** [nome, preço, unidade] — o nome é normalizado na carga, igual aos preços importados. */
const BASE: Array<[string, number, PrecoItem['unidade']]> = [
  // Hortifruti
  ['batata', 6.5, 'kg'],
  ['batata-doce', 7, 'kg'],
  ['cebola', 6, 'kg'],
  ['alho', 30, 'kg'],
  ['tomate', 9, 'kg'],
  ['cenoura', 6, 'kg'],
  ['abobrinha', 7, 'kg'],
  ['abóbora', 6, 'kg'],
  ['berinjela', 9, 'kg'],
  ['pimentão', 12, 'kg'],
  ['chuchu', 5, 'kg'],
  ['mandioca', 7, 'kg'],
  ['repolho', 5, 'kg'],
  ['couve', 6, 'kg'],
  ['brócolis', 14, 'kg'],
  ['alface', 8, 'kg'],
  ['espinafre', 12, 'kg'],
  ['salsinha', 20, 'kg'],
  ['cebolinha', 20, 'kg'],
  ['coentro', 20, 'kg'],
  ['manjericão', 40, 'kg'],
  ['gengibre', 20, 'kg'],
  ['limão', 7, 'kg'],
  ['laranja', 5, 'kg'],
  ['banana', 7, 'kg'],
  ['maçã', 10, 'kg'],
  ['mamão', 7, 'kg'],
  ['abacaxi', 8, 'unidade'],
  ['morango', 30, 'kg'],
  ['uva', 18, 'kg'],
  ['manga', 8, 'kg'],
  ['abacate', 9, 'kg'],
  ['pepino', 7, 'kg'],
  ['beterraba', 6, 'kg'],
  ['cogumelo', 60, 'kg'],

  // Açougue e peixaria
  ['carne moída', 32, 'kg'],
  ['patinho', 38, 'kg'],
  ['alcatra', 45, 'kg'],
  ['coxão mole', 40, 'kg'],
  ['picanha', 75, 'kg'],
  ['costela', 30, 'kg'],
  ['carne', 38, 'kg'],
  ['peito de frango', 20, 'kg'],
  ['coxa de frango', 14, 'kg'],
  ['sobrecoxa', 15, 'kg'],
  ['frango', 16, 'kg'],
  ['linguiça', 25, 'kg'],
  ['bacon', 35, 'kg'],
  ['lombo', 28, 'kg'],
  ['pernil', 24, 'kg'],
  ['salsicha', 16, 'kg'],
  ['tilápia', 40, 'kg'],
  ['salmão', 90, 'kg'],
  ['merluza', 32, 'kg'],
  ['camarão', 70, 'kg'],
  ['bacalhau', 90, 'kg'],
  ['peixe', 38, 'kg'],
  ['atum', 12, 'unidade'],
  ['sardinha', 8, 'unidade'],

  // Frios e laticínios
  ['leite', 5.5, 'l'],
  ['leite condensado', 8, 'unidade'],
  ['creme de leite', 5, 'unidade'],
  ['leite de coco', 7, 'l'],
  ['iogurte', 10, 'l'],
  ['manteiga', 55, 'kg'],
  ['margarina', 18, 'kg'],
  ['requeijão', 30, 'kg'],
  ['cream cheese', 45, 'kg'],
  ['queijo', 55, 'kg'],
  ['mussarela', 50, 'kg'],
  ['parmesão', 90, 'kg'],
  ['ricota', 30, 'kg'],
  ['presunto', 35, 'kg'],
  ['peito de peru', 45, 'kg'],
  ['mortadela', 20, 'kg'],
  ['ovo', 0.8, 'unidade'],

  // Mercearia, massas e grãos
  ['arroz', 6.5, 'kg'],
  ['feijão', 9, 'kg'],
  ['lentilha', 16, 'kg'],
  ['grão-de-bico', 18, 'kg'],
  ['macarrão', 8, 'kg'],
  ['farinha de trigo', 5.5, 'kg'],
  ['farinha de mandioca', 8, 'kg'],
  ['farinha', 6, 'kg'],
  ['fubá', 5, 'kg'],
  ['polvilho', 12, 'kg'],
  ['amido de milho', 16, 'kg'],
  ['aveia', 14, 'kg'],
  ['quinoa', 40, 'kg'],
  ['cuscuz', 7, 'kg'],
  ['açúcar', 5, 'kg'],
  ['açúcar mascavo', 14, 'kg'],
  ['adoçante', 60, 'l'],
  ['sal', 3, 'kg'],
  ['óleo', 9, 'l'],
  ['azeite', 45, 'l'],
  ['vinagre', 6, 'l'],
  ['chocolate em pó', 30, 'kg'],
  ['cacau', 60, 'kg'],
  ['chocolate', 60, 'kg'],
  ['coco ralado', 35, 'kg'],
  ['leite em pó', 40, 'kg'],
  ['mel', 40, 'kg'],
  ['geleia', 30, 'kg'],
  ['amendoim', 20, 'kg'],
  ['castanha', 80, 'kg'],
  ['nozes', 90, 'kg'],
  ['passas', 35, 'kg'],
  ['granola', 25, 'kg'],
  ['biscoito', 20, 'kg'],
  ['gelatina', 4, 'unidade'],
  ['fermento', 40, 'kg'],
  ['pão', 14, 'kg'],
  ['pão de forma', 9, 'unidade'],

  // Enlatados, conservas e molhos
  ['milho', 4.5, 'unidade'],
  ['ervilha', 4.5, 'unidade'],
  ['palmito', 15, 'unidade'],
  ['azeitona', 30, 'kg'],
  ['extrato de tomate', 5, 'unidade'],
  ['molho de tomate', 4, 'unidade'],
  ['tomate pelado', 9, 'unidade'],
  ['maionese', 16, 'kg'],
  ['ketchup', 16, 'kg'],
  ['mostarda', 16, 'kg'],
  ['molho de soja', 14, 'l'],

  // Temperos
  ['pimenta-do-reino', 120, 'kg'],
  ['orégano', 80, 'kg'],
  ['cominho', 80, 'kg'],
  ['colorau', 30, 'kg'],
  ['canela', 120, 'kg'],
  ['noz-moscada', 200, 'kg'],
  ['páprica', 100, 'kg'],
  ['curry', 100, 'kg'],
  ['louro', 150, 'kg'],
  ['caldo de galinha', 60, 'kg'],
  ['essência de baunilha', 120, 'l'],

  // Bebidas
  ['água', 2, 'l'],
  ['água de coco', 8, 'l'],
  ['suco', 8, 'l'],
  ['café', 50, 'kg'],
  ['vinho', 30, 'l'],
  ['cerveja', 8, 'l'],
];

/**
 * Tabela de preços-base no mesmo formato dos preços importados, para reaproveitar
 * `buscarPreco`/`custoLinha`. Nunca vai ao banco: entra só na consulta, depois dos
 * preços do usuário, que continuam tendo prioridade.
 */
export const PRECOS_BASE: PrecoItem[] = BASE.map(([item, precoUnitario, unidade]) => ({
  item,
  itemKey: normalizeItemKey(item),
  precoUnitario,
  unidade,
  atualizadoEm: 0,
  estimado: true,
}));
